In [1]:
import numpy as np

In [12]:
accuracy=np.zeros([3,3])
print(accuracy)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [16]:
for i in range(3):
    print(i)

    accuracy[0,i]=1+i
    accuracy[1,i]=2+i
    accuracy[2,i]=3+i
print(accuracy)

0
1
2
[[1. 2. 3.]
 [2. 3. 4.]
 [3. 4. 5.]]
